name: CI

on:
  pull_request:
    branches:
      - main

env:
  HUGO_VERSION: 0.140.2

# From https://github.com/aaseper/portfolio-hugo-ci-cd/blob/main/.github/workflows/deploy.yml
jobs:
  build:
    name: "Build site"
    runs-on: ubuntu-latest

    steps:
      - name: install-hugo-cli
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          hugo \
          --gc \
          --minify
